apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shopping-system.management-api.fullname" . }}
  labels:
    {{- include "shopping-system.labels" . | nindent 4 }}
data:
  APP_PORT: "{{ .Values.managementApi.service.port }}"
  LOG_LEVEL: {{ .Values.managementApi.logLevel }}  
  # Kafka Configs
  KAFKA_BOOTSTRAP_SERVERS: {{ include "shopping-system.kafka.bootstrap" . }}
  KAFKA_TOPIC: {{ (index .Values.kafka.provisioning.topics 0).name }}
  KAFKA_GROUP_ID: {{ .Values.managementApi.config.kafka.consumerGroup }}

  # Mongo Configs
  MONGO_HOSTNAME: {{ include "mongodb.service.nameOverride" .Subcharts.mongodb }}
  MONGO_PORT: "{{ .Values.mongodb.service.ports.mongodb }}"
  MONGO_DB_NAME: {{ .Values.managementApi.config.mongodb.database }}
  MONGO_COLLECTION_NAME: {{ .Values.managementApi.config.mongodb.collection }}