apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shopping-system.management-api.fullname" . }}
  labels:
    {{- include "shopping-system.labels" . | nindent 4 }}
data:

  LOG_LEVEL: {{ .Values.managementApi.logLevel }}  
  # Kafka Configs
  KAFKA_BOOTSTRAP_SERVERS: {{ .Release.Name }}-kafka.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.kafka.service.ports.client }}
  KAFKA_TOPIC: {{ (index .Values.kafka.provisioning.topics 0).name }}
  KAFKA_GROUP_ID: {{ .Values.managementApi.config.kafka.consumerGroup }}

  # Mongo Configs
  MONGO_HOSTNAME: "mongodb://{{ .Release.Name }}-mongodb.{{ .Release.Namespace }}.svc.cluster.local"
  MONGO_PORT: "{{ .Values.mongodb.service.ports.mongodb }}"
  MONGO_DB_NAME: {{ .Values.managementApi.config.mongodb.database }}
  MONGO_COLLECTION_NAME: {{ .Values.managementApi.config.mongodb.collection }}