apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shopping-system.web-server.fullname" . }}
  labels:
    {{- include "shopping-system.labels" . | nindent 4 }}
data:

  LOG_LEVEL: {{ .Values.webServer.logLevel }}  
  # Kafka Configs
  KAFKA_BOOTSTRAP_SERVERS: {{ .Release.Name }}-kafka.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.kafka.service.ports.client }}
  KAFKA_TOPIC: {{ (index .Values.kafka.provisioning.topics 0).name }}
