apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "management-api.fullname" . }}
  labels:
    {{- include "management-api.labels" . | nindent 4 }}
data:
  # Map 'camelCase' values to 'UPPERCASE' env vars explicitly
  LOG_LEVEL: {{ .Values.logLevel }}  
  # Kafka Configs
  # Note: We use the 'tpl' trick here in case you use the dynamic naming we discussed earlier!
  KAFKA_BROKERS: {{ tpl .Values.kafka.bootstrapServers . | quote }}
  KAFKA_TOPIC: {{ .Values.kafka.topic | quote }}
  KAFKA_CONSUMER_GROUP: {{ .Values.kafka.consumerGroup | quote }}